apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: odoo
  ports:
    - name: odoo
      port: 8069
      targetPort: 8069